swagger: "2.0"
info:
  description: "This is the documentation API for Hackernews Webside of group 13C of ASW."
  version: "1.0.0"
  title: "HackerNews"

host: "hackernews13c.herokuapp.com"
tags:
- name: "user"
  description: "The user of Hackernews"

schemes:
- "https"

paths:
  /users/{id}.json:
    get:
      summary: "User info"
      description: "Gets the information of the registered user."
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id of the user"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        default:
          description: "Uexpected Error!"
          schema:
            $ref: "#/definitions/Error"

  /threads/{id}.json:
    get:
      summary: "Threads of a user"
      description: "Gets all comments and replays of a user"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id of the user"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Thread"
        default:
          description: "Uexpected Error!"
          schema:
            $ref: "#/definitions/Error"

  /ask.json:
    get:
      summary: "All ask contributions"
      description: "Gets all contributions wuth url = null"
      produces:
      - "application/json"
      responses:
        200:
          description: "S'ha retornat totes les submissions de tipus 'Ask'."
          schema:
            $ref: "#/definitions/Contribution"
        default:
          description: "Error inesperat."
          schema:
            $ref: "#/definitions/Error"
  # GET comments by specific user
  /users/{id}/comments.json:
    get:
      summary: "Comments of a User"
      description: Retorna tots els comentaris de l'usuari amb id 'id'.
      parameters:
        - name: id
          in: path
          description: Identificador de l'usuari.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'han retornat els comentaris de l'usuari.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        404:
          description: L'usuari no existeix.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
   # GET url contributions list
  /contributions.json:
    get:
      description: Retorna un llistat de publicacions de tipus 'URL', es a dir, amb el camp url no buit ordenat cronologicament.
      responses:
        200:
          description: S'ha retornat totes les contributions de tipus 'URL'.
          schema:
            type: array
            items:
              $ref: '#/definitions/Contribution'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
  # GET specific contribution info
  /contributions/{id}.json:
    get:
      description: Retorna la informació d'un publicació.
      parameters:
        - name: id
          in: path
          description: Identificador de la publicació.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'ha retornat la publicació especificada.
          schema:
            $ref: '#/definitions/Contribution'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
            
  /contributions/{id}/comments.json:
    get:
      description: Retorna tots els comentaris de la contribution amb id 'id'.
      parameters:
        - name: id
          in: path
          description: Identificador de la publicació
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'han retornat tots els comentaris de la publicació.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'          
  
  # GET contributions by specific user          
  /{id}_contributions.json:
    get:
      description: Retorna totes els publicacions de l'usuari amb id 'id'.
      parameters:
        - name: id
          in: path
          description: Identificador de l'usuari.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'han retornat les publicacions de l'usuari especificat.
          schema:
            type: array
            items:
              $ref: '#/definitions/Contribution'
        404:
          description: L'usuari no existeix.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'        

      
  /comments.json:
    get:
      summary: "Comments"
      description: Retorna tots els comentaris.
      responses:
        200:
          description: S'han retornat tots els comentaris.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific comment info
  /comments/{id}.json:
    get:
      summary: "Specific comment"
      description: Retorna la informació d'un comentari.
      parameters:
        - name: id
          in: path
          description: Identificador del comentari.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'ha retornat el comentari.
          schema:
            $ref: '#/definitions/Comment'
        404:
          description: Comentari no existeix.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
    # GET specific comment info
  /comments/{id}/replies.json:
    get:
      description: Retorna la els replies del comentari amb id = id.
      parameters:
        - name: id
          in: path
          description: replies de comentari.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'han retornat els replies del comentari.
          schema:
            $ref: '#/definitions/Comment'
        404:
          description: Comentari no existeix.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
  
  # GET all replies
  /replies.json:
    get:
      summary: "Replies"
      description: Retorna totes les respostes.
      responses:
        200:
          description: S'han retornat totes les respostes.
          schema:
            type: array
            items:
              $ref: '#/definitions/Reply'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
            
  # GET specific reply info
  /replies/{id}.json:
    get:
      summary: "Specific reply"
      description: Retorna la informació d'una resposta especificada a un comentari.
      parameters:
        - name: id
          in: path
          description: Identificador de la resposta.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: S'ha retornat la resposta
          schema:
            $ref: '#/definitions/Reply'
        404:
          description: Resposta no existeix.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
definitions:
    User:
      type: object
      properties:
        id:
          type: integer
          description: identificador unic de l'usuari.
        name:
          type: string
          description: nom de l'usuari.
        email:
          type: string
          description: email de l'usuari.
        about:
          type: string
          description: descripció de l'usuari.
        created_at:
          type: string
          description: instant de creació de l'usuari.
        updated_at:
          type: string
          description: instant de lúltima actualització de lusuari.

    Contribution:
      type: object
      properties:
        id:
          type: integer
          description: identificador unic de la publicació.
        title:
          type: string
          description: títol de la publicació.
        url:
          type: string
          description: url associada a la publicació.
        text:
          type: string
          description: text associat a la publicació.
        user_id:
          type: integer
          description: identificador de l'usuari creador de la publicació.
        created_at:
          type: string
          description: instant de creació de la publicació.
        updated_at:
          type: string
          description: instant de l'última actualització de la publicació.

    Reply:
        type: object
        properties:
          id:
            type: integer
            description: identificador unic de la resposta.
          content:
            type: string
            description: contingut associat de la resposta.
          user_id:
            type: integer
            description: identificador de l'usuari creador de la resposta.
          comment_id:
            type: integer
            description: identificador del comentari relacionat.
          created_at:
            type: string
            description: instant de creació de la resposta.
          updated_at:
            type: string
            description: instant de l'última actualització de la resposta.
    Comment:
      type: object
      properties:
        id:
          type: integer
          description: identificador unic del comentari.
        content:
          type: string
          description: contingut associat del comentari.
        user_id:
          type: integer
          description: identificador de l'usuari creador del comentari.
        submission_id:
          type: integer
          description: identificador de la publicació relacionada.
        created_at:
          type: string
          description: instant de creació del comentari.
        updated_at:
          type: string
          description: instant de l'última actualització del comentari.

    Thread:
        type: object
        properties:
          comments:
            type: array
            description: llistat de comentaris de l'usuari.
            items:
              $ref: "#/definitions/Comment"
          replies:
            type: array
            description: llistat de respostes de l'usuari.
            items:
              $ref: "#/definitions/Reply"

    Error:
      type: object
      properties:
        code:
          type: integer
          description: codi de l'error.
          format: int32
        message:
          type: string
          description: missatge de l'error.
        fields:
          type: string
          description: camps de l'error.
